// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo3mQ2u4og1kMdnO2TPSTp1astBCZqVEY',
    appId: '1:120069458590:web:f3e1f3bca7b4a09b2d098f',
    messagingSenderId: '120069458590',
    projectId: 'healthify-2ba10',
    authDomain: 'healthify-2ba10.firebaseapp.com',
    storageBucket: 'healthify-2ba10.appspot.com',
    measurementId: 'G-CHE30XDW3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHVGAsFG-41HzF08fitg_tU9p8GMAs8Y',
    appId: '1:120069458590:android:ecf5f31ec216372f2d098f',
    messagingSenderId: '120069458590',
    projectId: 'healthify-2ba10',
    storageBucket: 'healthify-2ba10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_T_zKyLNAJHs2Eqz59WdNvFiu4Tli9iM',
    appId: '1:120069458590:ios:0874106454cd1d242d098f',
    messagingSenderId: '120069458590',
    projectId: 'healthify-2ba10',
    storageBucket: 'healthify-2ba10.appspot.com',
    iosBundleId: 'com.example.healthify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_T_zKyLNAJHs2Eqz59WdNvFiu4Tli9iM',
    appId: '1:120069458590:ios:386cdbc85801f5ba2d098f',
    messagingSenderId: '120069458590',
    projectId: 'healthify-2ba10',
    storageBucket: 'healthify-2ba10.appspot.com',
    iosBundleId: 'com.example.healthify.RunnerTests',
  );
}
